---
title: "simpleRegress"
author: "Michelle Coleman"
date: "April 11, 2021"
output:
    html_document:
     toc: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Bears regression model


### make a simple regression model-read in the data

```{r}
bears <- read.csv(file="BEARS.csv",header = TRUE)
```

## Model LENGTH ~ NECK  this is an example  

```{r}
simp <- lm(LENGTH~NECK,data=bears)
plot(LENGTH~NECK,data=bears)
abline(simp)
summary.lm(simp)
```

```{r}
simpHW <- lm(LENGTH~HEADWTH,data=bears)
plot(LENGTH~HEADWTH,data=bears)
abline(simpHW)
summary.lm(simpHW)
```

```{r}
simpHL <- lm(LENGTH~HEADLEN,data=bears)
plot(LENGTH~HEADLEN,data=bears)
abline(simpHL)
summary.lm(simpHL)
```

```{r}
simpW <- lm(LENGTH~WEIGHT,data=bears)
plot(LENGTH~WEIGHT,data=bears)
abline(simpW)
summary.lm(simpW)
```


```{r}
simpC <- lm(LENGTH~CHEST,data=bears)
plot(LENGTH~CHEST,data=bears)
abline(simpC)
summary.lm(simpC)
```

## now predict the length of a bear who has a neck of 17, 22 and 26





## Surely there is another variable that can better predict LENGTH than NECK. Find one and compare its performance to that of neck by it value of Adjusted-Rsquared (bigger is better).


















